export enum EControlNames {
  Category = 'category',
  Task = 'task',
  Date = 'date',
  Priority = 'priority',
  Tags = 'tags',
  AuthorId = 'authorId',
  Checked = 'checked',
  Image = 'image',
  Title = 'title',
  Price = 'price',
  Currency = 'currency',
  Link = 'link',
  Username = 'username',
  ProfilePhoto = 'profile_photo',
  Key = 'key',
}